### ISSUE TITLE
Improve the Splash Activity

### ISSUE THREAD

**Issue by alexandrepiveteau** [fennifith/Cleaner#1]
The splash activity should not be just a separate activity. I thought you learned a bit about how to [implement it correctly](http://cyrilmottier.com/2013/01/23/android-app-launching-made-gorgeous/), James.

**Comment by TheAndroidMaster** [comment]
Lolol I'm pretty sure I saw an article saying to make it separate. Not sure where though :P

**Comment by TheAndroidMaster** [comment]
@cadialex [Found it](https://www.bignerdranch.com/blog/splash-screens-the-right-way/). But yeah I see your point. Also I may have forgotten to finish the activity after starting the next one... :neutral_face:

**Comment by cadialex** [comment]
@TheAndroidMaster I'd say that the problem is that your splash screen is taking more time than what is actually required with the approach I suggested, since it relies on the birth (and death) of yet another Activity, which is quite CPU and memory-intensive, and adds an extra delay that you could get rid of.

According to me, it's a major issue for an application that is meant to stay on your device 10 seconds if it takes 10 more milliseconds to load!

😄
